microsoft/Generative-AI-for-beginners-dotnet

03-CoreGenerativeAITechniques/src/BasicChat-01MEAI/Program.cs

* project would not run in codespaces, error message: The type or namespace name 'StringBuilder' could not be found (are you missing a using directive or an assembly reference?). Added using stmt for System.Text and error message went away. 
* fixed one misspelling in last code comment

Lesson 03 / BasicChat-01MEAI - Missing using stmt for System.Text and fixing spelling error in comment.

---

03-CoreGenerativeAITechniques/02-retrieval-augmented-generation.md

Replace the outdated RAG explainer video link with the current one in the retrieval-augmented-generation documentation.

Update RAG explainer video link in documentation

---

01-IntroToGenAI/readme.md
02-SetupDevEnvironment/getting-started-ollama.md
02-SetupDevEnvironment/readme.md
04-PracticalSamples/readme.md
05-ResponsibleGenAI/readme.md

I identified and corrected trivial spelling errors. Since I'm just submitting fixes for trivial typos, I've combined modifications into a single PR where suitable. I hope you are okay with this.

I identified and corrected trivial spelling errors.

---

04-PracticalSamples/readme.md

This pull request includes updates to the `04-PracticalSamples/readme.md` file to improve the descriptions and add new sections for better clarity and detail. The most important changes include updating the eShopLite demos descriptions, adding new subsections for semantic search, and enhancing the real-time audio section.
Updates to eShopLite demos descriptions:
* Updated the description of eShopLite demos to emphasize the use of Generative AI capabilities and corrected the reference to Azure AI Foundry Models.
New sections and subsections:
* Added new subsections under eShopLite demos for "eShopLite with semantic search - In Memory" and "eShopLite with semantic search - Azure AI Search".
* Introduced a new section detailing the use of Azure AI Search in the eShopLite end-to-end demo, …

Bruno eshoplite samplesdoc update

---

03-CoreGenerativeAITechniques/src/CoreGenerativeAITechniques.sln
03-CoreGenerativeAITechniques/src/ReasoningLabs-01-SK/Program.cs
03-CoreGenerativeAITechniques/src/ReasoningLabs-01-SK/ReasoningLabs-01-SK.csproj

DETAILS
This pull request introduces a new project named `ReasoningLabs-01-SK` to the solution and includes initial implementation for using OpenAI's chat completion service. The most important changes include adding the new project to the solution, configuring the build settings, and implementing the initial code for the chat completion service.
* Added `ReasoningLabs-01-SK` project to the solution file `03-CoreGenerativeAITechniques.sln` [[1]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR56-R59) [[2]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR142-R145) [[3]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR170).
* Created `ReasoningLabs-01-SK.csproj` with necessary …

Add new projects to showcase the use of o3-mini model with SK

---

03-CoreGenerativeAITechniques/src/BasicChat-02SK/BasicChat-02SK.csproj
03-CoreGenerativeAITechniques/src/BasicChat-04OllamaSK/BasicChat-04OllamaSK.csproj
03-CoreGenerativeAITechniques/src/BasicChat-04OllamaSK/Program.cs
03-CoreGenerativeAITechniques/src/RAGSimple-02MEAIVectorsMemory/RAGSimple-02MEAIVectorsMemory.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-03MEAIVectorsAISearch/RAGSimple-03MEAIVectorsAISearch.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-04MEAIVectorsQdrant/RAGSimple-04MEAIVectorsQdrant.csproj
03-CoreGenerativeAITechniques/src/ReasoningLabs-01-SK/ReasoningLabs-01-SK.csproj
03-CoreGenerativeAITechniques/src/SKFunctions01/SKFunctions01.csproj

DETAILS
- Updated `Microsoft.SemanticKernel` to version `1.38.0` across multiple project files.
- Updated `Microsoft.SemanticKernel.Connectors.Ollama` to version `1.38.0-alpha`.
- Updated `Microsoft.SemanticKernel.Connectors.InMemory` to version `1.38.0-preview`.
- Updated `Microsoft.SemanticKernel.Connectors.AzureAISearch` to version `1.38.0-preview`.
- Updated `Microsoft.SemanticKernel.Connectors.Qdrant` to version `1.38.0-preview`.
- Upgraded `Microsoft.Extensions.Configuration.UserSecrets` to version `9.0.2`.
- Modified console output in `Program.cs` to include `modelId` in AI responses.

Update SemanticKernel packages and console output

---

.github/workflows/welcome-issue.yml
.github/workflows/welcome-pr.yml

DETAILS
Introduce GitHub Actions workflows for welcoming new issues and pull requests.
Each workflow triggers on opening an issue or pull request, adds a "needs-review" label,
and posts a thank-you comment to the author. Both workflows also auto-assign to
the user `elbruno` using the `pozil/auto-assign-issue` action.

Add workflows for welcoming issues and pull requests

---

03-CoreGenerativeAITechniques/src/RAGSimple-10SKOllama/Program.cs
03-CoreGenerativeAITechniques/src/RAGSimple-10SKOllama/RAGSimple-10SKOllama.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-10SKOllama/SpectreConsoleOutput.cs

DETAILS
- Updated `Program.cs` to include new using directives and refactored memory import process for improved readability.
- Enhanced output formatting to display token usage and relevant sources.
- Added `UserSecretsId` to `RAGSimple-10SKOllama.csproj` for sensitive information management and updated `Spectre.Console` package version.
- Introduced new methods in `SpectreConsoleOutput.cs` for better console output formatting and modified existing methods for flexibility.

Enhance memory management and console output

---

03-CoreGenerativeAITechniques/src/CoreGenerativeAITechniques.sln
03-CoreGenerativeAITechniques/src/RAGSimple-15Ollama-DeepSeekR1/Program.cs
03-CoreGenerativeAITechniques/src/RAGSimple-15Ollama-DeepSeekR1/RAGSimple-15Ollama-DeepSeekR1.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-15Ollama-DeepSeekR1/SpectreConsoleOutput.cs

DETAILS
Corrected the string describing Bruno's opinion on the movie "Eternals" from "Bruno don't like the super hero movie: Eternals" to "Bruno doesn't like the super hero movie: Eternals" to fix the grammatical error.

Add console RAG Ollama sample using Deepseek-R1

---

.github/workflows/validate-documentation-links.yml

Add GitHub workflow to validate documentation links and check for broken URLs

Add GitHub workflow to validate documentation links and check for broken URLs

---

02-SetupDevEnvironment/src/BasicChat-03Ollama/Program.cs
README.md

This pull request includes updates to the `Program.cs` file to provide additional information about testing models and updates to the `README.md` file to correct links to various learning resources.
* [`02-SetupDevEnvironment/src/BasicChat-03Ollama/Program.cs`](diffhunk://#diff-b7cf72c64b2a400b486953a3d84dac5df84f0118755e01d56814df2040921a69R3-R5): Added comments to provide guidance on testing with different models and the commands to download them.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L113-R116): Updated links for Generative AI and AI Agents courses to use short URLs instead of GitHub links.

Update README links and add model usage instructions in Program.cs for ollama models

---

03-CoreGenerativeAITechniques/01-lm-completions-functions.md

Simple fix of identation of markdown

Fix markup identation

---

02-SetupDevEnvironment/getting-started-azure-openai.md
02-SetupDevEnvironment/getting-started-ollama.md
03-CoreGenerativeAITechniques/02-retrieval-augmented-generation.md
translations/de/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/de/02-SetupDevEnvironment/getting-started-ollama.md
translations/es/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/es/02-SetupDevEnvironment/getting-started-ollama.md
translations/fr/02-SetupDevEnvironment/getting-started-ollama.md
translations/ja/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/ja/02-SetupDevEnvironment/getting-started-ollama.md
translations/ko/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/ko/02-SetupDevEnvironment/getting-started-ollama.md
translations/pt/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/pt/02-SetupDevEnvironment/getting-started-ollama.md
translations/tw/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/tw/02-SetupDevEnvironment/getting-started-ollama.md
translations/zh/02-SetupDevEnvironment/getting-started-azure-openai.md
translations/zh/02-SetupDevEnvironment/getting-started-ollama.md

DETAILS
Updated getting started documentation to include links to Azure AI Foundry resources and deployment guides. Changes include English and translations in German, Spanish, French, Japanese, Korean, and Chinese. Added new community resources related to AI applications and retrieval-augmented generation (RAG). Standardized link formatting across all documents.

Update documentation, remove locale from urls, add contributors resources

---

02-SetupDevEnvironment/getting-started-ollama.md
README.md

Fix by reported in https://github.com/microsoft/Generative-AI-for-beginners-dotnet/issues/84

Bruno-fixbrokenlinks

---

.devcontainer/Ollama/devcontainer.json
02-SetupDevEnvironment/getting-started-ollama.md
02-SetupDevEnvironment/readme.md
02-SetupDevEnvironment/src/BasicChat-03Ollama/Program.cs
03-CoreGenerativeAITechniques/src/BasicChat-03Ollama/Program.cs
03-CoreGenerativeAITechniques/src/BasicChat-04OllamaSK/Program.cs
03-CoreGenerativeAITechniques/src/RAGSimple-10SKOllama/Program.cs
03-CoreGenerativeAITechniques/src/RAGSimple-15Ollama-DeepSeekR1/Program.cs
README.md

This pull request focuses on updating the models used in various parts of the project from "phi3.5" to "phi4-mini". The changes span multiple files, including configuration files, documentation, and source code.
* [`.devcontainer/Ollama/devcontainer.json`](diffhunk://#diff-d20db3202faaa49e43f90be65dcc7f0d032b5ba9baa2fc2b63701d1036d6edcbL40-R40): Updated the `postCreateCommand` to pull the "phi4-mini" model instead of "phi3.5".
* [`02-SetupDevEnvironment/getting-started-ollama.md`](diffhunk://#diff-99729da752cb4101bf677e54d1e1eb4cbdb4da8cc5f8564f73e59ceb6e0387bcL66-R66): Updated documentation to mention the "phi4-mini" model and its usage in sample apps. [[1]](diffhunk://#diff-99729da752cb4101bf677e54d1e1eb4cbdb4da8cc5f8564f73e59ceb6e0387bcL66-R66) …

Adding "phi4-mini" in samples, codespaces and docs

---

translations/ja/01-IntroToGenAI/readme.md

https://github.com/microsoft/Generative-AI-for-beginners-dotnet/blob/main/translations/ja/01-IntroToGenAI/readme.md 
#PingMSFTDocs

Update readme.md (Untranslated "Semantic Kernel"→ "セマンティック カーネル")

---

03-CoreGenerativeAITechniques/src/Vision-01MEAI-GitHubModels/Vision-01MEAI-GitHubModels.csproj

DETAILS
Updated `Vision-01MEAI-GitHubModels.csproj` to target .NET 9.0, and upgraded `Microsoft.Extensions.Configuration.UserSecrets` from version 9.0.2 to 9.0.3. The project structure and included images remain unchanged.

Update project to .NET 9.0 and package version

---

03-CoreGenerativeAITechniques/src/RAGSimple-01SK/Program.cs

Since this is a pure text application, a vision-capable model is unnecessary.

fix: using llama3.2 instead of its vision model

---

02-SetupDevEnvironment/src/BasicChat-01MEAI/BasicChat-01MEAI.csproj
02-SetupDevEnvironment/src/BasicChat-01MEAI/Program.cs
02-SetupDevEnvironment/src/BasicChat-03Ollama/BasicChat-03Ollama.csproj
03-CoreGenerativeAITechniques/src/AIToolkit-02-MEAI-Chat/AIToolkit-02-MEAI-Chat.csproj
03-CoreGenerativeAITechniques/src/BasicChat-01MEAI/BasicChat-01MEAI.csproj
03-CoreGenerativeAITechniques/src/BasicChat-01MEAI/Program.cs
03-CoreGenerativeAITechniques/src/BasicChat-03Ollama/BasicChat-03Ollama.csproj
03-CoreGenerativeAITechniques/src/BasicChat-03Ollama/Program.cs
03-CoreGenerativeAITechniques/src/DockerModels-02-MEAI-Chat/DockerModels-02-MEAI-Chat.csproj
03-CoreGenerativeAITechniques/src/MEAIFunctions/MEAIFunctions.csproj
03-CoreGenerativeAITechniques/src/MEAIFunctions/Program.cs
03-CoreGenerativeAITechniques/src/MEAIFunctionsOllama/MEAIFunctionsOllama.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-02MEAIVectorsMemory/RAGSimple-02MEAIVectorsMemory.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-03MEAIVectorsAISearch/RAGSimple-03MEAIVectorsAISearch.csproj
03-CoreGenerativeAITechniques/src/RAGSimple-04MEAIVectorsQdrant/RAGSimple-04MEAIVectorsQdrant.csproj
03-CoreGenerativeAITechniques/src/Vision-01MEAI-GitHubModels/Program.cs
03-CoreGenerativeAITechniques/src/Vision-01MEAI-GitHubModels/Vision-01MEAI-GitHubModels.csproj
03-CoreGenerativeAITechniques/src/Vision-02MEAI-Ollama/Program.cs
03-CoreGenerativeAITechniques/src/Vision-02MEAI-Ollama/Vision-02MEAI-Ollama.csproj
03-CoreGenerativeAITechniques/src/Vision-03MEAI-AOAI/Program.cs
03-CoreGenerativeAITechniques/src/Vision-03MEAI-AOAI/Vision-03MEAI-AOAI.csproj
04-PracticalSamples/src/src/McpSample.Chat/Components/Pages/Home.razor
04-PracticalSamples/src/src/McpSample.Chat/McpSample.BlazorChat.csproj

Update to M.E.AI 9.4.3-preview.1.25230.7

---

03-CoreGenerativeAITechniques/src/AgentLabs-01-Simple/AgentLabs-01-Simple.csproj
03-CoreGenerativeAITechniques/src/AgentLabs-01-Simple/Program.cs

DETAILS
- Updated `AgentLabs-01-Simple.csproj` to replace the package reference for `Azure.AI.Projects` with `Azure.AI.Agents.Persistent` and updated versions of `Azure.AI.Projects` and `Microsoft.Extensions.Configuration.UserSecrets`.
- Refactored `Program.cs` to use `PersistentAgentsClient` instead of `AgentsClient`, including new user secrets for tenant ID and endpoint retrieval.
- Changed agent model from `"gpt-4o-mini"` to `"gpt-4.1"` and updated message handling to use asynchronous methods.
- Added agent deletion after use to clean up resources.

Update Azure packages and refactor agent handling

---

03-CoreGenerativeAITechniques/src/CoreGenerativeAITechniques.sln
03-CoreGenerativeAITechniques/src/VideoGeneration-AzureSora-01/Program.cs
03-CoreGenerativeAITechniques/src/VideoGeneration-AzureSora-01/VideoGeneration-AzureSora-01.csproj
10-WhatsNew/readme.md
README.md

This pull request introduces a new feature for video generation using the Azure OpenAI Sora model and updates relevant documentation and project files. The changes include adding a new lesson sample, implementing the video generation functionality, and updating the course materials to reflect the new capabilities.
* Added a new project, `VideoGeneration-AzureSora-01`, to the solution file `CoreGenerativeAITechniques.sln`. This includes the necessary configurations for building and debugging the video generation demo. [[1]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR84-R87) [[2]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR446-R457) [[3]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6 …

Add Sora video generation sample

---

03-CoreGenerativeAITechniques/src/VideoGeneration-AzureSoraSDK-02/Program.cs
03-CoreGenerativeAITechniques/src/VideoGeneration-AzureSoraSDK-02/VideoGeneration-AzureSoraSDK-02.csproj

Added a console application demonstrating video generation using the [AzureSoraSDK](https://github.com/DrHazemAli/AzureSoraSDK) NuGet package, complementing the existing REST API sample (VideoGeneration-AzureSora-01).
This sample provides developers with a production-ready starting point for integrating Azure SORA video generation into their .NET applications, using AzureSoraSDK package.

Added Video Generation using AzureSoraSDK

---

03-CoreGenerativeAITechniques/src/BasicChat-06OpenAIAPIs/BasicChat-06OpenAIAPIs.csproj
03-CoreGenerativeAITechniques/src/BasicChat-06OpenAIAPIs/Program.cs
03-CoreGenerativeAITechniques/src/CoreGenerativeAITechniques.sln

This pull request introduces a new project, `BasicChat-06OpenAIAPIs`, to the solution and implements functionality for sentiment analysis using OpenAI's GPT model. Key changes include the addition of the project file, updates to the solution file, and implementation of the main program logic.
* Created a new project file, `BasicChat-06OpenAIAPIs.csproj`, targeting `.NET 9.0` and including dependencies for OpenAI and Microsoft Extensions libraries.
* Updated the solution file, `CoreGenerativeAITechniques.sln`, to include the new project and its build configurations for various platforms. [[1]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefL3-R4) [[2]](diffhunk://#diff-27363b9e0973c3e94d2990d1e494ac20cefd25eeb908ff79a26dcc43e6d6feefR108-R109) …

Add BasicChat-06OpenAIAPIs project for sentiment analysis

---

03-CoreGenerativeAITechniques/src/BasicChat-07Ollama-gpt-oss/BasicChat-07Ollama-gpt-oss.csproj
03-CoreGenerativeAITechniques/src/BasicChat-07Ollama-gpt-oss/Program.cs
03-CoreGenerativeAITechniques/src/CoreGenerativeAITechniques.sln
README.md

This pull request adds a new sample project demonstrating how to use the Ollama GPT-OSS model for basic chat functionality. The main changes include introducing the new project with its dependencies, implementing a simple chat client example, and updating the solution file to include and configure the new project.
**New project addition:**
* Added new project `BasicChat-07Ollama-gpt-oss` with references to `Microsoft.Extensions.AI.Ollama` and user secrets packages.
* Implemented a sample chat client in `Program.cs` that connects to a local Ollama instance using the `gpt-oss:20b` model and prints the model's response to a sample prompt.
**Solution file updates:**
* Registered the new project in the solution file and configured its build settings for all supported platforms and …

Add BasicChat-07Ollama-gpt-oss project and initial implementation

---

03-CoreGenerativeAITechniques/src/Audio-02-RealTimeAudio/Audio-02-RealTimeAudio.csproj
03-CoreGenerativeAITechniques/src/Audio-02-RealTimeAudio/Program.cs

Upgraded Azure SDK packages to latest versions, including `Azure.AI.OpenAI` (2.3.0-beta.2), `Azure.Identity` (1.15.0), and `Microsoft.Extensions.Configuration.UserSecrets` (9.0.9).
Replaced `RealtimeConversationClient` with `RealtimeClient` to align with updated SDK. Refactored session configuration by introducing `CreateConversationSessionOptions` and added a default prompt for improved usability.
Updated event handling to use new `RealtimeUpdate` types and replaced deprecated API calls with `GetRealtimeClient`. Simplified model retrieval with a new `GetModel` method.
Improved code clarity by consolidating configuration logic and grouping related methods. Updated warning suppression to address new SDK warnings.

Refactor and update RealtimeClient integration
